#!/bin/bash

set -e

topd=$(pwd)/root
tstamp=$(date +%Y-%m-%d_%H-%M-%S)
rnd=$RANDOM
wkdir="${topd}/work-${tstamp}-${rnd}"
ddir="${topd}/data"
sdir="${topd}/src"

docker run -v "${ddir}":/root/data:ro \
       -v "${sdir}":/root/src:ro \
       -v "${wkdir}":/root/work \
       eamon/swineflows-correlation /root/src/run-analysis

user=$(id -u)
group=$(id -g)

# Currently, $wdir and its contents are always owned by root, so
sudo chown -hR ${user}:${group} $wkdir 
