#!/bin/bash

set -e

cwd=$(pwd)
tstamp=$(date +%Y-%m-%d_%H-%M-%S)
rnd=$RANDOM
wkdir="${cwd}/work-${tstamp}-${rnd}"
ddir="${cwd}/data"
sdir="${cwd}/src"

docker run -i -t -v "${ddir}":/root/data:ro \
       -v "${sdir}":/root/src:ro \
       -v "${wkdir}":/root/work \
       eamon/swineflows-correlation 

user=$(id -u)
group=$(id -g)

# Currently, $wdir and its contents are always owned by root, so
#sudo chown -hR ${user}:${group} $wkdir 
